
name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
          fetch-depth: 0
      - name: Re-attach HEAD
        run: |
          git checkout "${GITHUB_REF:11}"
          git config --global user.email "bilt-ci@tayar.org"
          git config --global user.name "Bilt CI"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - name: Bilt
        run: |
          # cat ~/.npmrc
          # cat .npmrc
          npm install -g @bilt/cli
          bilt -m "build from CI" --no-before
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
